// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package amplifyx

import (
	"context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	config, err := provideAWSConfig(ctx)
	if err != nil {
		return nil, err
	}
	client := provideAWSAmplifyClient(config)
	app := provideApp(client)
	return app, nil
}
